# typed: false
# frozen_string_literal: true

# This file was generated by Gemini.
class Awstok < Formula
  desc "A tool to manage AWS CodeArtifact tokens for NuGet"
  homepage "https://github.com/paulafahmy-t/awstok"
  
  url "https://github.com/paulafahmy-t/awstok/archive/refs/tags/v1.0.1.tar.gz"
  version "1.0.1"
  sha256 "053e8cecc9c958d97b73c4fe0ffbc611b8b317a37ac262b678703deb52a63dcd"

  # Formula dependencies
  depends_on "awscli"
  depends_on "coreutils" # for gtimeout
  depends_on "dotnet"
  depends_on "saml2aws"

  def install
    # This command will move the script to Homebrew's binary directory,
    # rename it to 'awstok', and make it executable.
    bin.install "awstok.sh" => "awstok"
  end

  service do
    run [opt_bin/"awstok", "check"]
    run_type :cron
    cron "30 9 * * *"
    log_path var/"log/awstok.log"
    error_log_path var/"log/awstok.log"
  end

  test do
    # A simple test to check if the command runs and shows the help message.
    assert_match "Usage: #{bin}/awstok {command}", shell_output("#{bin}/awstok help")
  end
end
